apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "1"
      nvidia.network-operator.revision: "1835718431"
    creationTimestamp: "2025-11-21T11:49:17Z"
    generation: 1
    labels:
      app: mofed-rhcos4.18-554bdbd7cf
      mofed-ds-format-version: "1"
      nvidia.com/ofed-driver: ""
      nvidia.network-operator.state: state-OFED
    name: mofed-rhcos4.18-554bdbd7cf-ds
    namespace: nvidia-network-operator
    ownerReferences:
    - apiVersion: mellanox.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: NicClusterPolicy
      name: nic-cluster-policy
      uid: 2af20f2f-9484-4706-897d-59ac37c14218
    resourceVersion: "452298"
    uid: 93cc93cf-8d02-407c-81c3-5463178a5302
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: mofed-rhcos4.18-554bdbd7cf
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mofed-rhcos4.18-554bdbd7cf
          kernel: 5.14.0-427.96.1.el9_4.aarch64_64k
          nvidia.com/ofed-driver: ""
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: nvidia.com/ofed-driver
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        containers:
        - env:
          - name: DTK_OCP_DRIVER_BUILD
            value: "true"
          - name: DTK_OCP_NIC_SHARED_DIR
            value: /mnt/shared-doca-driver-toolkit
          - name: CREATE_IFNAMES_UDEV
            value: "true"
          - name: NVIDIA_NIC_DRIVERS_INVENTORY_PATH
            value: /mnt/drivers-inventory
          image: registry-arm.slcm.partner.lab:8443/nvidia/certified-operator/nvidia/mellanox/doca-driver-container:25.07-0.9.7.0-rhcos4.18-arm64
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - lsmod | grep mlx5_core
            failureThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: mofed-container
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - lsmod | grep mlx5_core
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}
          securityContext:
            privileged: true
            seLinuxOptions:
              level: s0
          startupProbe:
            exec:
              command:
              - sh
              - -c
              - ls /run/mellanox/drivers/.driver-ready
            failureThreshold: 60
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /run/mellanox/drivers
            mountPropagation: Bidirectional
            name: run-mlnx-ofed
          - mountPath: /etc/network
            name: etc-network
          - mountPath: /host/etc
            name: host-etc
          - mountPath: /host/usr
            name: host-usr
          - mountPath: /host/lib/udev
            name: host-udev
          - mountPath: /run/udev
            name: host-run-udev
            readOnly: true
          - mountPath: /host/lib/modules
            name: host-lib-modules
          - mountPath: /mnt/drivers-inventory
            name: drivers-inventory
          - mountPath: /etc/modprobe.d/ib_core.conf
            name: host-ib-core
          - mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
            name: ocp-network-operator-trusted-ca
            readOnly: true
            subPath: tls-ca-bundle.pem
          - mountPath: /etc/yum.repos.d/registry-arm.slcm.partner.lab..8443
            name: arm-registry-config
            readOnly: true
            subPath: registry-arm.slcm.partner.lab..8443
          - mountPath: /mnt/shared-doca-driver-toolkit
            name: shared-doca-driver-toolkit
        - args:
          - |
            until [ -f /mnt/shared-doca-driver-toolkit/dtk_start_compile ]; do
              echo Waiting for mofed-container container to prepare the shared directory
              sleep 3
            done
            exec /mnt/shared-doca-driver-toolkit/dtk_nic_driver_build.sh
          command:
          - bash
          - -xc
          env:
          - name: DTK_OCP_NIC_SHARED_DIR
            value: /mnt/shared-doca-driver-toolkit
          - name: CREATE_IFNAMES_UDEV
            value: "true"
          - name: NVIDIA_NIC_DRIVERS_INVENTORY_PATH
            value: /mnt/drivers-inventory
          image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:75798070ee8bba72891c1ef66858117d352b2b98a4072c4ce5e6424d03845930
          imagePullPolicy: IfNotPresent
          name: openshift-driver-toolkit-ctr
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
            name: ocp-network-operator-trusted-ca
            readOnly: true
            subPath: tls-ca-bundle.pem
          - mountPath: /etc/yum.repos.d/registry-arm.slcm.partner.lab..8443
            name: arm-registry-config
            readOnly: true
            subPath: registry-arm.slcm.partner.lab..8443
          - mountPath: /mnt/shared-doca-driver-toolkit
            name: shared-doca-driver-toolkit
        dnsPolicy: ClusterFirst
        hostNetwork: true
        initContainers:
        - args:
          - --node-name
          - $(NODE_NAME)
          - --configmap-name
          - ofed-init-container-config
          - --configmap-namespace
          - nvidia-network-operator
          - --configmap-key
          - config.json
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          image: nvcr.io/nvidia/mellanox/network-operator-init-container@sha256:02ee60ac6ee163acc97706bd4229d268f608a95bcbcb6fccee90ceb1d8a6c62b
          imagePullPolicy: IfNotPresent
          name: network-operator-init-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        nodeSelector:
          feature.node.kubernetes.io/kernel-version.full: 5.14.0-427.96.1.el9_4.aarch64_64k
          feature.node.kubernetes.io/pci-15b3.present: "true"
          feature.node.kubernetes.io/system-os_release.ID: rhcos
          feature.node.kubernetes.io/system-os_release.OSTREE_VERSION: 418.94.202510230424-0
          feature.node.kubernetes.io/system-os_release.VERSION_ID: "4.18"
        priorityClassName: system-node-critical
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: ofed-driver
        serviceAccountName: ofed-driver
        terminationGracePeriodSeconds: 300
        tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
        volumes:
        - hostPath:
            path: /run/mellanox/drivers
            type: ""
          name: run-mlnx-ofed
        - hostPath:
            path: /etc/network
            type: ""
          name: etc-network
        - hostPath:
            path: /etc
            type: ""
          name: host-etc
        - hostPath:
            path: /usr
            type: ""
          name: host-usr
        - hostPath:
            path: /lib/udev
            type: ""
          name: host-udev
        - hostPath:
            path: /run/udev
            type: ""
          name: host-run-udev
        - hostPath:
            path: /lib/modules
            type: ""
          name: host-lib-modules
        - hostPath:
            path: /var/opt/mofed-container/inventory
            type: DirectoryOrCreate
          name: drivers-inventory
        - hostPath:
            path: /etc/modprobe.d/ib_core.conf
            type: FileOrCreate
          name: host-ib-core
        - configMap:
            defaultMode: 420
            items:
            - key: ca-bundle.crt
              path: tls-ca-bundle.pem
            name: ocp-network-operator-trusted-ca
          name: ocp-network-operator-trusted-ca
        - configMap:
            defaultMode: 420
            items:
            - key: registry-arm.slcm.partner.lab..8443
              path: registry-arm.slcm.partner.lab..8443
            name: arm-registry-config
          name: arm-registry-config
        - emptyDir: {}
          name: shared-doca-driver-toolkit
    updateStrategy:
      type: OnDelete
  status:
    currentNumberScheduled: 1
    desiredNumberScheduled: 1
    numberAvailable: 1
    numberMisscheduled: 0
    numberReady: 1
    observedGeneration: 1
    updatedNumberScheduled: 1
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "1"
      nvidia.network-operator.revision: "3705805267"
    creationTimestamp: "2025-11-21T08:43:12Z"
    generation: 1
    labels:
      nvidia.network-operator.state: state-RDMA-device-plugin
    name: rdma-shared-dp-ds
    namespace: nvidia-network-operator
    ownerReferences:
    - apiVersion: mellanox.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: NicClusterPolicy
      name: nic-cluster-policy
      uid: 2af20f2f-9484-4706-897d-59ac37c14218
    resourceVersion: "452325"
    uid: 3bc1ad34-57dc-4469-baa2-f334d10f9777
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: rdma-shared-dp
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: rdma-shared-dp
      spec:
        containers:
        - command:
          - /bin/k8s-rdma-shared-dp
          image: ghcr.io/mellanox/k8s-rdma-shared-dev-plugin:1eb5ab7f4b6f0cf89c954cf7ac8eb2e6fb2290a4f5f57417136a5302f20b12c8
          imagePullPolicy: IfNotPresent
          name: rdma-shared-dp
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/kubelet/device-plugins
            name: device-plugin
          - mountPath: /var/lib/kubelet/plugins_registry
            name: plugins-registry
          - mountPath: /k8s-rdma-shared-dev-plugin
            name: config
          - mountPath: /dev/
            name: devs
        dnsPolicy: ClusterFirst
        hostNetwork: true
        initContainers:
        - args:
          - until lsmod | grep mlx5_core; do echo waiting for OFED drivers to be loaded;
            sleep 30; done
          command:
          - sh
          - -c
          image: ghcr.io/mellanox/k8s-rdma-shared-dev-plugin:1eb5ab7f4b6f0cf89c954cf7ac8eb2e6fb2290a4f5f57417136a5302f20b12c8
          imagePullPolicy: IfNotPresent
          name: ofed-driver-validation
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        nodeSelector:
          feature.node.kubernetes.io/pci-15b3.present: "true"
          network.nvidia.com/operator.mofed.wait: "false"
        priorityClassName: system-node-critical
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: rdma-shared
        serviceAccountName: rdma-shared
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
        volumes:
        - hostPath:
            path: /var/lib/kubelet/device-plugins
            type: ""
          name: device-plugin
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: ""
          name: plugins-registry
        - configMap:
            defaultMode: 420
            items:
            - key: config.json
              path: config.json
            name: rdma-devices
          name: config
        - hostPath:
            path: /dev/
            type: ""
          name: devs
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 1
    desiredNumberScheduled: 1
    numberAvailable: 1
    numberMisscheduled: 0
    numberReady: 1
    observedGeneration: 1
    updatedNumberScheduled: 1
kind: List
metadata:
  resourceVersion: ""
